export const styles = {
  mainLayout: {
    display: 'flex',
    minHeight: '100vh',
    bgcolor: '#F8FAFC',
    color: '#1E293B',
    fontFamily: "'Inter', sans-serif",
  },
  contentArea: {
    flexGrow: 1,
    p: { xs: 2.5, md: 4 },
    width: { xs: '100%', md: 'calc(100% - 260px)' },
    minHeight: '100vh',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
  },
  // Toolbar and filters
  filterCard: {
    bgcolor: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    p: 3,
    boxShadow: '0 1px 3px rgba(15, 23, 42, 0.05)',
  },
  filterHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 2,
    flexWrap: 'wrap',
  },
  filterTitle: {
    display: 'flex',
    alignItems: 'center',
    gap: 1,
    fontFamily: "'Inter', sans-serif",
    fontSize: '16px',
    fontWeight: 600,
    color: '#1E2875',
  },
  filterToggleBtn: {
    color: '#1E2875',
    borderColor: '#1E2875',
    textTransform: 'none',
    fontWeight: 600,
    fontSize: '13px',
    borderRadius: '8px',
    '&:hover': {
      bgcolor: 'rgba(30, 40, 117, 0.06)',
      borderColor: '#1E2875',
    },
  },
  // Section blocks
  sectionBlock: {
    mt: 2,
    mb: 3,
  },
  sectionHeader: {
    display: 'flex',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    mb: 2,
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 700,
    color: '#1E2875',
    fontFamily: "'Inter', sans-serif",
  },
  sectionHint: {
    fontSize: '13px',
    color: '#64748B',
  },
  // Report Cards
  reportCard: {
    bgcolor: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    p: 2.5,
    height: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    gap: 1.5,
    transition: 'all 0.2s ease-in-out',
    '&:hover': {
      boxShadow: '0 8px 20px rgba(15, 23, 42, 0.08)',
      transform: 'translateY(-2px)',
      borderColor: '#CBD5E1',
    },
  },
  reportBadge: (color) => ({
    fontSize: '11px',
    fontWeight: 700,
    borderRadius: '999px',
    px: 1.5,
    py: 0.4,
    bgcolor: `${color}1A`,
    color: color,
    whiteSpace: 'nowrap',
    letterSpacing: '0.02em',
  }),
  chip: {
    fontSize: '11.5px',
    fontWeight: 500,
    color: '#475569',
    bgcolor: '#F1F5F9',
    border: '1px solid #E2E8F0',
    borderRadius: '999px',
    px: 1.2,
    py: 0.3,
    display: 'inline-flex',
    alignItems: 'center',
  },
  // Constructor / Wizard
  stepperContainer: {
    display: 'flex',
    alignItems: 'center',
    mb: 3.5,
    flexWrap: 'wrap',
    gap: 1,
  },
  stepCircle: (isActive, isDone) => ({
    width: 32,
    height: 32,
    borderRadius: '50%',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '13px',
    fontWeight: 700,
    bgcolor: isDone ? '#1E2875' : isActive ? '#FFFFFF' : '#FFFFFF',
    color: isDone ? '#FFFFFF' : isActive ? '#1E2875' : '#94A3B8',
    border: `2px solid ${isDone ? '#1E2875' : isActive ? '#1E2875' : '#CBD5E1'}`,
    boxShadow: isActive ? '0 0 0 4px rgba(30, 40, 117, 0.12)' : 'none',
    transition: 'all 0.2s ease-in-out',
  }),
  stepConnector: (isDone) => ({
    flex: '0 0 32px',
    height: 2,
    bgcolor: isDone ? '#1E2875' : '#E2E8F0',
    mx: 1,
    borderRadius: 1,
  }),
  builderCard: {
    bgcolor: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    p: 3,
    boxShadow: '0 1px 3px rgba(15, 23, 42, 0.04)',
  },
  summaryPanel: {
    bgcolor: '#FFFFFF',
    border: '1px solid #E2E8F0',
    borderRadius: '12px',
    p: 3,
    position: 'sticky',
    top: 24,
    boxShadow: '0 1px 3px rgba(15, 23, 42, 0.04)',
  },
  // Format Card Selector
  formatCard: (isSelected) => ({
    flex: 1,
    border: `2px solid ${isSelected ? '#1E2875' : '#E2E8F0'}`,
    bgcolor: isSelected ? 'rgba(30, 40, 117, 0.04)' : '#FFFFFF',
    borderRadius: '12px',
    p: 2.5,
    textAlign: 'center',
    cursor: 'pointer',
    transition: 'all 0.15s ease-in-out',
    '&:hover': {
      borderColor: isSelected ? '#1E2875' : '#94A3B8',
    },
  }),
  // Document Sheet A4 Preview
  docPage: {
    width: '794px',
    maxWidth: '100%',
    minHeight: '1000px',
    bgcolor: '#FFFFFF',
    boxShadow: '0 8px 30px rgba(15, 23, 42, 0.12)',
    borderRadius: '4px',
    p: { xs: 3, sm: 5, md: 6 },
    fontFamily: "'Inter', sans-serif",
    position: 'relative',
    mx: 'auto',
  },
  floatingHelpButton: {
    position: 'fixed',
    bottom: 24,
    right: 24,
    bgcolor: '#1E2875',
    color: '#ffffff',
    width: 48,
    height: 48,
    boxShadow: '0 4px 12px rgba(30, 40, 117, 0.25)',
    zIndex: 99,
    '&:hover': {
      bgcolor: '#131a52',
    },
  },
};
